version: '3.8'
services:
  backend-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  node_modules: